[package]
name = "tensorrt-llm"
version.workspace = true
edition.workspace = true
description = "Rust bindings for the TensorRT-LLM Executor API with Candle tensor support."
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
candle-core.workspace = true
cudarc = { workspace = true, optional = true }
half.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
tensorrt.workspace = true
tensorrt-llm-sys.workspace = true

[features]
default = []
cuda = ["candle-core/cuda", "dep:cudarc", "tensorrt/cuda"]
